#!/usr/bin/env bash
# theme.sh — Convert Ghostty theme configs to CSS custom properties.
# Usage: ./theme.sh --light path/to/light.conf --dark path/to/dark.conf

set -euo pipefail

OUT="_colors.css"
LIGHT_CONF=""
DARK_CONF=""

# ── argument parsing ───────────────────────────────────────────────────────────

while [[ $# -gt 0 ]]; do
  case "$1" in
    --light) LIGHT_CONF="${2:-}"; shift 2 ;;
    --dark)  DARK_CONF="${2:-}";  shift 2 ;;
    *) echo "Unknown argument: $1" >&2; exit 1 ;;
  esac
done

if [[ -z "$LIGHT_CONF" || -z "$DARK_CONF" ]]; then
  echo "Usage: $0 --light <ghostty-config> --dark <ghostty-config>" >&2
  exit 1
fi

for f in "$LIGHT_CONF" "$DARK_CONF"; do
  if [[ ! -f "$f" ]]; then
    echo "Error: file not found: $f" >&2
    exit 1
  fi
done

# ── helpers ──────────────────────────────────────────────────────────────────

extract() {
  # extract <key> <conf> — returns the hex value for a simple key = #xxxxxx line
  local key="$1" conf="$2"
  grep -E "^[[:space:]]*${key}[[:space:]]*=" "$conf" \
    | tail -1 \
    | sed -E 's/.*=[[:space:]]*(#[0-9a-fA-F]{6,8}).*/\1/'
}

extract_palette() {
  # extract_palette <index> <conf> — returns hex for  palette = N=#xxxxxx
  local idx="$1" conf="$2"
  grep -E "^[[:space:]]*palette[[:space:]]*=[[:space:]]*${idx}=" "$conf" \
    | tail -1 \
    | sed -E 's/.*=[[:space:]]*(#[0-9a-fA-F]{6,8}).*/\1/'
}

# ── emit a theme block ────────────────────────────────────────────────────────

emit_vars() {
  # emit_vars <conf> — prints CSS variable declarations (no selector wrapper)
  local conf="$1"

  local BG FG SEL_BG SEL_FG CURSOR
  BG=$(extract "background" "$conf")
  FG=$(extract "foreground" "$conf")
  SEL_BG=$(extract "selection-background" "$conf")
  SEL_FG=$(extract "selection-foreground" "$conf")
  CURSOR=$(extract "cursor-color" "$conf")

  [[ -n "$BG"     ]] && echo "  --color-background:          $BG;"
  [[ -n "$FG"     ]] && echo "  --color-foreground:          $FG;"
  [[ -n "$SEL_BG" ]] && echo "  --color-selection-bg:        $SEL_BG;"
  [[ -n "$SEL_FG" ]] && echo "  --color-selection-fg:        $SEL_FG;"
  [[ -n "$CURSOR" ]] && echo "  --color-cursor:              $CURSOR;"
  echo ""

  declare -A NAMES=(
    [0]="black"       [8]="bright-black"
    [1]="red"         [9]="bright-red"
    [2]="green"       [10]="bright-green"
    [3]="yellow"      [11]="bright-yellow"
    [4]="blue"        [12]="bright-blue"
    [5]="magenta"     [13]="bright-magenta"
    [6]="cyan"        [14]="bright-cyan"
    [7]="white"       [15]="bright-white"
  )

  for i in $(seq 0 15); do
    hex=$(extract_palette "$i" "$conf")
    if [[ -n "$hex" ]]; then
      name="${NAMES[$i]}"
      printf "  --color-%-2s  /* %-14s */  %s;\n" "$i:" "$name" "$hex"
    fi
  done

  echo ""
  echo "  /* Semantic aliases — used by style.css */"
  echo "  --color-accent:   var(--color-4);   /* blue  */"
  echo "  --color-muted:    var(--color-8);   /* bright-black / comments */"
  echo "  --color-success:  var(--color-2);   /* green */"
  echo "  --color-error:    var(--color-1);   /* red   */"
  echo "  --color-warning:  var(--color-3);   /* yellow */"
}

# ── emit CSS ──────────────────────────────────────────────────────────────────

{
  echo "/* Auto-generated by theme.sh — do not edit by hand */"
  echo "/* Light source: $LIGHT_CONF */"
  echo "/* Dark source:  $DARK_CONF */"
  echo ""

  echo "/* ── Light theme ──────────────────────────────────────────────── */"
  echo ":root, [data-theme=\"light\"] {"
  emit_vars "$LIGHT_CONF"
  echo "}"
  echo ""

  # Capture dark vars once, emit in two places
  DARK_VARS=$(emit_vars "$DARK_CONF")

  echo "/* ── Dark theme (system preference, no-JS fallback) ──────────── */"
  echo "@media (prefers-color-scheme: dark) {"
  echo "  :root:not([data-theme=\"light\"]) {"
  echo "$DARK_VARS" | sed 's/^/  /'
  echo "  }"
  echo "}"
  echo ""

  echo "/* ── Dark theme (explicit toggle override) ────────────────────── */"
  echo "[data-theme=\"dark\"] {"
  echo "$DARK_VARS"
  echo "}"
} > "$OUT"

echo "Written: $OUT" >&2
