#!/usr/bin/env bash
# theme.sh — Convert a Ghostty theme config to CSS custom properties.
# Usage: ./theme.sh path/to/ghostty.conf > _colors.css
#   or:  ./theme.sh path/to/ghostty.conf   (writes _colors.css in current dir)

set -euo pipefail

CONF="${1:-}"
OUT="_colors.css"

if [[ -z "$CONF" ]]; then
  echo "Usage: $0 <ghostty-config-file>" >&2
  exit 1
fi

if [[ ! -f "$CONF" ]]; then
  echo "Error: file not found: $CONF" >&2
  exit 1
fi

# ── helpers ──────────────────────────────────────────────────────────────────

extract() {
  # extract_value <key> — returns the hex value for a simple key = #xxxxxx line
  local key="$1"
  grep -E "^[[:space:]]*${key}[[:space:]]*=" "$CONF" \
    | tail -1 \
    | sed -E 's/.*=[[:space:]]*(#[0-9a-fA-F]{6,8}).*/\1/'
}

extract_palette() {
  # extract_palette <index> — returns hex for  palette = N=#xxxxxx
  local idx="$1"
  grep -E "^[[:space:]]*palette[[:space:]]*=[[:space:]]*${idx}=" "$CONF" \
    | tail -1 \
    | sed -E 's/.*=[[:space:]]*(#[0-9a-fA-F]{6,8}).*/\1/'
}

# ── parse ─────────────────────────────────────────────────────────────────────

BG=$(extract "background")
FG=$(extract "foreground")
SEL_BG=$(extract "selection-background")
SEL_FG=$(extract "selection-foreground")
CURSOR=$(extract "cursor-color")

# ── emit CSS ──────────────────────────────────────────────────────────────────

{
  echo "/* Auto-generated by theme.sh — do not edit by hand */"
  echo "/* Source: $CONF */"
  echo ""
  echo ":root {"

  [[ -n "$BG"     ]] && echo "  --color-background:          $BG;"
  [[ -n "$FG"     ]] && echo "  --color-foreground:          $FG;"
  [[ -n "$SEL_BG" ]] && echo "  --color-selection-bg:        $SEL_BG;"
  [[ -n "$SEL_FG" ]] && echo "  --color-selection-fg:        $SEL_FG;"
  [[ -n "$CURSOR" ]] && echo "  --color-cursor:              $CURSOR;"
  echo ""

  # Named semantic aliases for the standard 16-color ANSI palette
  declare -A NAMES=(
    [0]="black"       [8]="bright-black"
    [1]="red"         [9]="bright-red"
    [2]="green"       [10]="bright-green"
    [3]="yellow"      [11]="bright-yellow"
    [4]="blue"        [12]="bright-blue"
    [5]="magenta"     [13]="bright-magenta"
    [6]="cyan"        [14]="bright-cyan"
    [7]="white"       [15]="bright-white"
  )

  for i in $(seq 0 15); do
    hex=$(extract_palette "$i")
    if [[ -n "$hex" ]]; then
      name="${NAMES[$i]}"
      printf "  --color-%-2s  /* %-14s */  %s;\n" "$i:" "$name" "$hex"
    fi
  done

  echo ""
  echo "  /* Semantic aliases — used by style.css */"
  echo "  --color-accent:   var(--color-4);   /* blue  */"
  echo "  --color-muted:    var(--color-8);   /* bright-black / comments */"
  echo "  --color-success:  var(--color-2);   /* green */"
  echo "  --color-error:    var(--color-1);   /* red   */"
  echo "  --color-warning:  var(--color-3);   /* yellow */"
  echo "}"
} > "$OUT"

echo "Written: $OUT" >&2
